2021-07-01 21:30:51.697 -03:00 [INF] Iniciando a WebAPI
2021-07-01 21:30:53.546 -03:00 [INF] Entity Framework Core 5.0.6 initialized 'LCContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
2021-07-01 21:31:03.849 -03:00 [INF] Executed DbCommand (106ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-07-01 21:31:04.419 -03:00 [INF] Executed DbCommand (555ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
2021-07-01 21:31:04.423 -03:00 [INF] Executed DbCommand (1ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-07-01 21:31:04.424 -03:00 [INF] Executed DbCommand (0ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
2021-07-01 21:31:04.756 -03:00 [INF] Executed DbCommand (2ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
2021-07-01 21:31:04.778 -03:00 [INF] No migrations were applied. The database is already up to date.
2021-07-01 21:31:04.780 -03:00 [INF] Executed DbCommand (0ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-07-01 21:31:12.449 -03:00 [INF] Executed DbCommand (7,667ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
2021-07-01 21:31:12.576 -03:00 [INF] Application started. Press Ctrl+C to shut down.
2021-07-01 21:31:12.576 -03:00 [INF] Hosting environment: Development
2021-07-01 21:31:12.576 -03:00 [INF] Content root path: C:\DEV\LegalClinic\LC.WebApi
2021-07-01 21:31:12.594 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/  
2021-07-01 21:31:12.643 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/index.html  
2021-07-01 21:31:12.651 -03:00 [INF] Request finished in 59.6331ms 301 
2021-07-01 21:31:12.689 -03:00 [INF] Request finished in 46.5105ms 200 text/html;charset=utf-8
2021-07-01 21:31:12.708 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/swagger-ui-bundle.js  
2021-07-01 21:31:12.708 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/swagger-ui.css  
2021-07-01 21:31:12.708 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/swagger-ui-standalone-preset.js  
2021-07-01 21:31:12.805 -03:00 [INF] Sending file. Request path: '/swagger-ui.css'. Physical path: 'N/A'
2021-07-01 21:31:12.805 -03:00 [INF] Sending file. Request path: '/swagger-ui-standalone-preset.js'. Physical path: 'N/A'
2021-07-01 21:31:12.807 -03:00 [INF] Request finished in 98.5932ms 200 text/css
2021-07-01 21:31:12.807 -03:00 [INF] Request finished in 98.5932ms 200 application/javascript
2021-07-01 21:31:14.567 -03:00 [INF] Sending file. Request path: '/swagger-ui-bundle.js'. Physical path: 'N/A'
2021-07-01 21:31:14.568 -03:00 [INF] Request finished in 1859.5603ms 200 application/javascript
2021-07-01 21:31:14.850 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/swagger/v1/swagger.json  
2021-07-01 21:31:18.318 -03:00 [INF] Request starting HTTP/1.1 GET https://localhost:44375/swagger-ui-bundle.js.map  
2021-07-01 21:31:18.325 -03:00 [INF] Request starting HTTP/1.1 GET https://localhost:44375/swagger-ui-standalone-preset.js.map  
2021-07-01 21:31:18.351 -03:00 [INF] Request finished in 25.7659ms 404 
2021-07-01 21:31:18.351 -03:00 [INF] Request finished in 32.747ms 404 
2021-07-01 21:31:20.106 -03:00 [INF] Request finished in 5256.5198ms 200 application/json;charset=utf-8
2021-07-01 21:32:34.010 -03:00 [INF] Iniciando a WebAPI
2021-07-01 21:32:35.635 -03:00 [INF] Entity Framework Core 5.0.6 initialized 'LCContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
2021-07-01 21:32:36.117 -03:00 [INF] Executed DbCommand (21ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-07-01 21:32:36.211 -03:00 [INF] Executed DbCommand (73ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
2021-07-01 21:32:36.214 -03:00 [INF] Executed DbCommand (1ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-07-01 21:32:36.215 -03:00 [INF] Executed DbCommand (0ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT OBJECT_ID(N'[__EFMigrationsHistory]');
2021-07-01 21:32:36.245 -03:00 [INF] Executed DbCommand (3ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT [MigrationId], [ProductVersion]
FROM [__EFMigrationsHistory]
ORDER BY [MigrationId];
2021-07-01 21:32:36.264 -03:00 [INF] No migrations were applied. The database is already up to date.
2021-07-01 21:32:36.265 -03:00 [INF] Executed DbCommand (0ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
SELECT 1
2021-07-01 21:32:36.278 -03:00 [INF] Executed DbCommand (11ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']

IF EXISTS
    (SELECT *
     FROM [sys].[objects] o
     WHERE [o].[type] = 'U'
     AND [o].[is_ms_shipped] = 0
     AND NOT EXISTS (SELECT *
         FROM [sys].[extended_properties] AS [ep]
         WHERE [ep].[major_id] = [o].[object_id]
             AND [ep].[minor_id] = 0
             AND [ep].[class] = 1
             AND [ep].[name] = N'microsoft_database_tools_support'
    )
)
SELECT 1 ELSE SELECT 0
2021-07-01 21:32:36.441 -03:00 [INF] Application started. Press Ctrl+C to shut down.
2021-07-01 21:32:36.442 -03:00 [INF] Hosting environment: Development
2021-07-01 21:32:36.442 -03:00 [INF] Content root path: C:\DEV\LegalClinic\LC.WebApi
2021-07-01 21:32:36.478 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/  
2021-07-01 21:32:36.545 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/index.html  
2021-07-01 21:32:36.547 -03:00 [INF] Request finished in 77.5223ms 301 
2021-07-01 21:32:36.588 -03:00 [INF] Request finished in 43.3306ms 200 text/html;charset=utf-8
2021-07-01 21:32:36.607 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/swagger-ui-bundle.js  
2021-07-01 21:32:36.607 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/swagger-ui-standalone-preset.js  
2021-07-01 21:32:36.607 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/swagger-ui.css  
2021-07-01 21:32:36.663 -03:00 [INF] Sending file. Request path: '/swagger-ui.css'. Physical path: 'N/A'
2021-07-01 21:32:36.663 -03:00 [INF] Sending file. Request path: '/swagger-ui-bundle.js'. Physical path: 'N/A'
2021-07-01 21:32:36.663 -03:00 [INF] Sending file. Request path: '/swagger-ui-standalone-preset.js'. Physical path: 'N/A'
2021-07-01 21:32:36.665 -03:00 [INF] Request finished in 57.7716ms 200 text/css
2021-07-01 21:32:36.665 -03:00 [INF] Request finished in 57.7716ms 200 application/javascript
2021-07-01 21:32:36.665 -03:00 [INF] Request finished in 57.7492ms 200 application/javascript
2021-07-01 21:32:36.857 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/swagger/v1/swagger.json  
2021-07-01 21:32:36.983 -03:00 [INF] Request finished in 125.9404ms 200 application/json;charset=utf-8
2021-07-01 21:32:37.101 -03:00 [INF] Request starting HTTP/1.1 GET https://localhost:44375/swagger-ui-bundle.js.map  
2021-07-01 21:32:37.132 -03:00 [INF] Request starting HTTP/1.1 GET https://localhost:44375/swagger-ui-standalone-preset.js.map  
2021-07-01 21:32:37.137 -03:00 [INF] Request finished in 5.7844ms 404 
2021-07-01 21:32:37.137 -03:00 [INF] Request finished in 36.3952ms 404 
2021-07-01 21:32:49.177 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:32:49.210 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:32:49.856 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:32:50.863 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 1002.9681ms
2021-07-01 21:32:50.867 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:32:50.868 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:32:51.529 -03:00 [INF] Request finished in 2351.6904ms 500 text/plain
2021-07-01 21:33:54.325 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:54.327 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:54.328 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:54.418 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 89.5851ms
2021-07-01 21:33:54.418 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:54.419 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:54.424 -03:00 [INF] Request finished in 102.1212ms 500 text/plain
2021-07-01 21:33:54.606 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:54.608 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:54.608 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:54.638 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 29.5673ms
2021-07-01 21:33:54.639 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:54.640 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:54.643 -03:00 [INF] Request finished in 36.8813ms 500 text/plain
2021-07-01 21:33:54.772 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:54.773 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:54.773 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:54.799 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 25.6762ms
2021-07-01 21:33:54.799 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:54.800 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:54.803 -03:00 [INF] Request finished in 30.7588ms 500 text/plain
2021-07-01 21:33:54.969 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:54.971 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:54.971 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:55.000 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 28.362ms
2021-07-01 21:33:55.000 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:55.001 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:55.003 -03:00 [INF] Request finished in 34.0048ms 500 text/plain
2021-07-01 21:33:55.135 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:55.136 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:55.136 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:55.163 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 27.3731ms
2021-07-01 21:33:55.164 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:55.164 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:55.166 -03:00 [INF] Request finished in 31.0168ms 500 text/plain
2021-07-01 21:33:55.273 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:55.273 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:55.273 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:55.297 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 23.9993ms
2021-07-01 21:33:55.298 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:55.299 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:55.305 -03:00 [INF] Request finished in 31.5447ms 500 text/plain
2021-07-01 21:33:55.398 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:55.398 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:55.399 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:55.423 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 24.4839ms
2021-07-01 21:33:55.424 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:55.425 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:55.429 -03:00 [INF] Request finished in 31.532ms 500 text/plain
2021-07-01 21:33:55.590 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:55.590 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:55.590 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:55.614 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 23.6801ms
2021-07-01 21:33:55.614 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:55.615 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:55.617 -03:00 [INF] Request finished in 26.7183ms 500 text/plain
2021-07-01 21:33:55.767 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:55.768 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:55.769 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:55.793 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 23.506ms
2021-07-01 21:33:55.793 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:55.794 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:55.797 -03:00 [INF] Request finished in 29.5217ms 500 text/plain
2021-07-01 21:33:55.965 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:55.965 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:55.966 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:55.993 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 27.4791ms
2021-07-01 21:33:55.994 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:55.994 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:55.996 -03:00 [INF] Request finished in 31.1516ms 500 text/plain
2021-07-01 21:33:56.141 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:56.141 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:56.142 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:56.168 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 25.8159ms
2021-07-01 21:33:56.168 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:56.169 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:56.174 -03:00 [INF] Request finished in 33.2681ms 500 text/plain
2021-07-01 21:33:56.364 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:56.364 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:56.365 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:56.396 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 31.2724ms
2021-07-01 21:33:56.396 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:56.397 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:56.399 -03:00 [INF] Request finished in 35.4589ms 500 text/plain
2021-07-01 21:33:56.507 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:56.507 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:56.507 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:56.533 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 25.4668ms
2021-07-01 21:33:56.533 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:56.533 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:56.535 -03:00 [INF] Request finished in 28.116ms 500 text/plain
2021-07-01 21:33:56.640 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:56.640 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:56.640 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:56.664 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 23.7981ms
2021-07-01 21:33:56.664 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:56.665 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:56.666 -03:00 [INF] Request finished in 26.2798ms 500 text/plain
2021-07-01 21:33:56.765 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:56.766 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:56.766 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:56.787 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 21.1579ms
2021-07-01 21:33:56.787 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:56.788 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:56.789 -03:00 [INF] Request finished in 23.9885ms 500 text/plain
2021-07-01 21:33:56.901 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:56.902 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:56.902 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:56.928 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 26.3809ms
2021-07-01 21:33:56.929 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:56.929 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:56.932 -03:00 [INF] Request finished in 30.4299ms 500 text/plain
2021-07-01 21:33:57.025 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:57.025 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:57.026 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:57.049 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 23.2973ms
2021-07-01 21:33:57.050 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:57.050 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:57.053 -03:00 [INF] Request finished in 27.9153ms 500 text/plain
2021-07-01 21:33:57.156 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:33:57.157 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:57.157 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:33:57.184 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 27.2159ms
2021-07-01 21:33:57.185 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:33:57.185 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:33:57.205 -03:00 [INF] Request finished in 48.6386ms 500 text/plain
2021-07-01 21:34:06.982 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:34:06.982 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:06.982 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:34:07.009 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 26.7858ms
2021-07-01 21:34:07.009 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:07.010 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:34:07.012 -03:00 [INF] Request finished in 30.1671ms 500 text/plain
2021-07-01 21:34:07.136 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:34:07.137 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:07.137 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:34:07.159 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 22.163ms
2021-07-01 21:34:07.160 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:07.160 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:34:07.162 -03:00 [INF] Request finished in 25.7098ms 500 text/plain
2021-07-01 21:34:07.281 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:34:07.281 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:07.281 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:34:07.309 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 27.8059ms
2021-07-01 21:34:07.309 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:07.310 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:34:07.312 -03:00 [INF] Request finished in 31.1459ms 500 text/plain
2021-07-01 21:34:07.564 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:34:07.564 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:07.565 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:34:07.590 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 25.1327ms
2021-07-01 21:34:07.590 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:07.591 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:34:07.593 -03:00 [INF] Request finished in 28.8222ms 500 text/plain
2021-07-01 21:34:07.708 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:34:07.708 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:07.709 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:34:07.740 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 31.2297ms
2021-07-01 21:34:07.740 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:07.741 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:34:07.742 -03:00 [INF] Request finished in 34.5389ms 500 text/plain
2021-07-01 21:34:07.844 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:34:07.844 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:07.845 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:34:07.871 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 26.0614ms
2021-07-01 21:34:07.871 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:07.872 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:34:07.873 -03:00 [INF] Request finished in 29.1362ms 500 text/plain
2021-07-01 21:34:07.961 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:34:07.961 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:07.961 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:34:07.985 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 24.2947ms
2021-07-01 21:34:07.986 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:07.987 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:34:07.989 -03:00 [INF] Request finished in 28.4042ms 500 text/plain
2021-07-01 21:34:08.070 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:34:08.070 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:08.070 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:34:08.096 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 25.9466ms
2021-07-01 21:34:08.096 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:08.097 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:34:08.099 -03:00 [INF] Request finished in 29.7427ms 500 text/plain
2021-07-01 21:34:08.211 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:34:08.211 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:08.211 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:34:08.234 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 22.8707ms
2021-07-01 21:34:08.235 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:08.236 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:34:08.237 -03:00 [INF] Request finished in 26.6282ms 500 text/plain
2021-07-01 21:34:08.315 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:34:08.315 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:08.316 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:34:08.339 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 23.2039ms
2021-07-01 21:34:08.339 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:08.340 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:34:08.341 -03:00 [INF] Request finished in 25.828ms 500 text/plain
2021-07-01 21:34:08.436 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:34:08.436 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:08.437 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:34:08.460 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 23.4856ms
2021-07-01 21:34:08.460 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:08.461 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2021-07-01 21:34:08.462 -03:00 [INF] Request finished in 26.2088ms 500 text/plain
2021-07-01 21:34:08.644 -03:00 [INF] Request starting HTTP/2.0 GET https://localhost:44375/api/Customers  
2021-07-01 21:34:08.644 -03:00 [INF] Executing endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:08.644 -03:00 [INF] Route matched with {action = "Get", controller = "Customers"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Get() on controller LC.WebApi.Controllers.CustomersController (LC.WebApi).
2021-07-01 21:34:08.670 -03:00 [INF] Executed action LC.WebApi.Controllers.CustomersController.Get (LC.WebApi) in 25.3618ms
2021-07-01 21:34:08.670 -03:00 [INF] Executed endpoint 'LC.WebApi.Controllers.CustomersController.Get (LC.WebApi)'
2021-07-01 21:34:08.671 -03:00 [ERR] An unhandled exception has occurred while executing the request.
System.Exception: Erro teste
   at LC.WebApi.Controllers.CustomersController.Get() in C:\DEV\LegalClinic\LC.WebApi\Controllers\CustomersController.cs:line 31
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
